### ISSUE TITLE
Questions about CRID format

### ISSUE THREAD

**Issue by yueyangyang** [seancfoley/IPAddress#114] opened 2023-10-30 06:08 UTC
I want to get the start and end addresses.
```java
String ip = "160.160.0.1/16";
IPAddress ipAddress = new IPAddressString(ip).getAddress();
System.out.println(ipAddress.isMultiple());
System.out.println(ipAddress.getLower());
System.out.println(ipAddress.getUpper());
```
Console print result is:
```
false
160.160.0.1/16
160.160.0.1/16
```

Here's what I was hoping for:
```
true
192.168.0.0/16
192.168.255.255/16
```

Am I using it the wrong way?

**Comment by seancfoley** [comment] 2023-10-31 03:34
160.160.0.1/16 is the same address as 160.160.0.1.  So, it's a single address, and the upper and lower are both 160.160.0.1/16, also the same.  That is because the host of 160.160.0.1/16 is 1, not 0.

What you want is
```
IPAddress ipAddress = new IPAddressString("160.160.0.1/16").toPrefixBlock().getAddress();
```
or 
```
// host is zero, so it is the prefix block of 192.168.0.0/16 to 192.168.255.255/16
IPAddress ipAddress = new IPAddressString("160.160.0.0/16").getAddress(); 
```

This a duplicate of issue https://github.com/seancfoley/IPAddress/issues/92, issue https://github.com/seancfoley/IPAddress/issues/60, issue https://github.com/seancfoley/IPAddress/issues/57, issue https://github.com/seancfoley/IPAddress/issues/54, issue https://github.com/seancfoley/IPAddress/issues/51, issue https://github.com/seancfoley/IPAddress/issues/45, issue https://github.com/seancfoley/IPAddress/issues/40, issue https://github.com/seancfoley/IPAddress/issues/30, issue https://github.com/seancfoley/IPAddress/issues/26, and also similar to issue https://github.com/seancfoley/IPAddress/issues/53 and issue https://github.com/seancfoley/IPAddress/issues/39.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#containment-within-the-enclosing-cidr-prefix-block).

**Closed by seancfoley** 2023-10-31 03:34 UTC

**Comment by yueyangyang** [comment] 2023-10-31 05:46
Thank you very much. Using the following method got me what I wanted.
```java
String ip = "160.160.0.1/16";
IPAddress ipAddress = new IPAddressString(ip).getAddress().toPrefixBlock();;
System.out.println(ipAddress.isMultiple());
System.out.println(ipAddress.getLower());
System.out.println(ipAddress.getUpper());
```
```
true
192.168.0.0/16
192.168.255.255/16
```
