### ISSUE TITLE
java.lang.NullPointerException in IPAddressString

### ISSUE THREAD

**Issue by r0man** [seancfoley/IPAddress#2] opened 2017-03-13 13:44 UTC
Hello @seancfoley,

the IPAddressString class raises a NullPointerException when passing it an invalid netmask like `127.0.0.1/x` and calling `isValid` on it. I think it should return false instead.

Roman.

**Comment by seancfoley** [comment] 2017-03-13 17:11
Hello Roman, 
I've tried this out and I cannot reproduce the issue you describe.  Can you provide a test case, either a source file or just pasting the code in here?  If not, can you give me the stack trace of the NullPointerException?

**Comment by r0man** [comment] 2017-03-13 19:18
@seancfoley Yes, sorry. I should have provided an example. Here is it:

```
new IPAddressString("127.0.0.1/x").isValid();
```

raises the following exception:

```
Unhandled java.lang.NullPointerException
IPAddressStringParameters.java:  495  inet.ipaddr.IPAddressStringParameters/toBuilder
IPv6AddressStringParameters.java:   46  inet.ipaddr.ipv6.IPv6AddressStringParameters/toBuilder
IPAddressStringParameters.java:  495  inet.ipaddr.IPAddressStringParameters/toBuilder
IPAddressStringParameters.java:  483  inet.ipaddr.IPAddressStringParameters/toBuilder
            Validator.java:  844  inet.ipaddr.format.validate.Validator/toMaskOptions
            Validator.java:  781  inet.ipaddr.format.validate.Validator/parseQualifier
            Validator.java:   85  inet.ipaddr.format.validate.Validator/validateAddressImpl
            Validator.java:   67  inet.ipaddr.format.validate.Validator/validateAddress
      IPAddressString.java:  426  inet.ipaddr.IPAddressString/validate
      IPAddressString.java:  375  inet.ipaddr.IPAddressString/validate
      IPAddressString.java:  579  inet.ipaddr.IPAddressString/toAddress
      IPAddressString.java:  531  inet.ipaddr.IPAddressString/getAddress
                      REPL:   22  access-watch.address/eval25117
                      REPL:   22  access-watch.address/eval25117
             Compiler.java: 6978  clojure.lang.Compiler/eval
             Compiler.java: 6941  clojure.lang.Compiler/eval
                  core.clj: 3187  clojure.core/eval
                  core.clj: 3183  clojure.core/eval
                  main.clj:  242  clojure.main/repl/read-eval-print/fn
                  main.clj:  242  clojure.main/repl/read-eval-print
                  main.clj:  260  clojure.main/repl/fn
                  main.clj:  260  clojure.main/repl
                  main.clj:  176  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj:  652  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj: 1963  clojure.core/with-bindings*
                  core.clj: 1963  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run
```

I would have expected it to return false.

**Comment by seancfoley** [comment] 2017-03-14 20:34
Hi, I've published a fix, the fix is in both master and v2 branches.  It is also a github release v2.0.1 where there is a jar available, shortly the release will go up on maven.

**Comment by r0man** [comment] 2017-03-15 08:48
@seancfoley Great. Thanks for the quick response and the release!

**Comment by seancfoley** [comment] 2017-03-20 06:07
Not a problem - I do want to root out any bugs and also plug any associated holes in my testing, so thanks for listing the issue.  Released to maven.  Closing.

**Closed by seancfoley** 2017-03-20 06:07 UTC
