### ISSUE TITLE
why 2222 is a valid IPV4 address?

### ISSUE THREAD

**Issue by maxpaynebupt** [seancfoley/IPAddress#42] opened 2020-06-06 02:39 UTC
IPAddressString srcAddressString = new IPAddressString("2222");
srcAddressString.isValid();

**Comment by seancfoley** [comment] 2020-06-06 12:34
Addresses of 11 non-segmented digits or less are IPv4.  2222 is the address 0.0.8.174. Duplicate of issue #19

**Closed by seancfoley** 2020-06-06 12:34 UTC
