### ISSUE TITLE
IPv6, Net Mask, contains()

### ISSUE THREAD

**Issue by matzepf** [seancfoley/IPAddress#120] opened 2024-01-25 18:36 UTC
Sorry, maybe I missed something with IPv6 but why do I get this?
```
IPAddress address2 = new IPAddressString("1:2:3::0/32").getAddress();
IPAddress address3 = new IPAddressString("1:2:3::0/48").getAddress();
System.out.println(address2.contains(new IPAddressString("1:2:3::12").getAddress()));
System.out.println(address3.contains(new IPAddressString("1:2:3::12").getAddress()));
```
Output:
```
false
true
```
Every net mask < 48 results in false.

**Comment by seancfoley** [comment] 2024-01-26 02:58
What you want is
```
IPAddress address2 = new IPAddressString("1:2::0/32").getAddress();
```
or
```
IPAddress address2 = new IPAddressString("1:2:3::0/32").getAddress().toPrefixBlock();
```
1:2:3::0/32 is not considered a subnet because its host is not zero, the host is 3:0:0:0:0:0.  The subnet is 1:2::0/32.
1:2:3::0/32 is the same as 1:2:3::0.  1:2:3::0 does not contain 1:2:3::12.

This is a duplicate of issue https://github.com/seancfoley/IPAddress/issues/114, issue https://github.com/seancfoley/IPAddress/issues/92, issue https://github.com/seancfoley/IPAddress/issues/60, issue https://github.com/seancfoley/IPAddress/issues/57, issue https://github.com/seancfoley/IPAddress/issues/54, issue https://github.com/seancfoley/IPAddress/issues/51, issue https://github.com/seancfoley/IPAddress/issues/45, issue https://github.com/seancfoley/IPAddress/issues/40, issue https://github.com/seancfoley/IPAddress/issues/30, issue https://github.com/seancfoley/IPAddress/issues/26, issue https://github.com/seancfoley/IPAddress/issues/53 and issue https://github.com/seancfoley/IPAddress/issues/39.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#containment-within-the-enclosing-cidr-prefix-block).

**Closed by seancfoley** 2024-01-26 02:58 UTC
