### ISSUE TITLE
Wrong contains logic in IpAddressString

### ISSUE THREAD

**Issue by eugine** [seancfoley/IPAddress#60] opened 2021-04-22 13:23 UTC
A junit test with comparison to SubnetUtils from apache common.net. 
Both cases for IpAddressString fail. On the same time SubnetUtils cases are green. 

`import inet.ipaddr.IPAddressString;
import org.apache.commons.net.util.SubnetUtils;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class IpAddressStringTest {

    private static final String CASE1_NETWORK = "213.41.21.20/24";
    private static final String CASE1_IP = "213.41.21.1";

    private static final String CASE2_NETWORK = "8.8.8.0/8";
    private static final String CASE2_IP = "8.1.0.3";

    @Test
    void ipaddress_contains_case_1() {
        var network = new IPAddressString(CASE1_NETWORK);
        assertTrue(network.contains(new IPAddressString(CASE1_IP)));
    }

    @Test
    void ipaddress_contains_case_2() {
        var network = new IPAddressString(CASE2_NETWORK);
        assertTrue(network.contains(new IPAddressString(CASE2_IP)));
    }

    @Test
    void apache_commons_subnetutils_case_1() {
        var network = new SubnetUtils(CASE1_NETWORK);
        assertTrue(network.getInfo().isInRange(CASE1_IP));
    }

    @Test
    void apache_commons_subnetutils_case_2() {
        var network  = new SubnetUtils(CASE2_NETWORK);
        assertTrue(network.getInfo().isInRange(CASE2_IP));
    }

}`

**Comment by seancfoley** [comment] 2021-04-22 15:37
This is not a bug, so closing.

This a duplicate of issue #57, issue #54, issue #51, issue #45,  issue #40, issue #30, issue #26, and also similar to issue #53 and issue #39, none of which were bugs either.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#containment-within-the-enclosing-cidr-prefix-block).

**Closed by seancfoley** 2021-04-22 15:37 UTC

**Comment by eugine** [comment] 2021-04-26 11:59
Thanks for the update. 

Just a note: the amount of duplicates clearly indicates that the behavior is misleading.

**Comment by eugine** [comment] 2021-04-26 15:35
10k users use your library... 
I would use another stats: 17% (10/58) of the bugs in this project are about the same issue. 

btw, what is the argument not to throw an exception on parsing such input: `parse("1.2.3.4/16")`  ?

**Comment by seancfoley** [comment] 2021-04-26 15:48
You did not read the wiki links I provided, where I say "this is explained in this wiki entry".  What a surprise.  And you pointed out that this project has very few bugs.  Thank you.
