### ISSUE TITLE
Throw ArrayIndexOutOfBoundsException with a prefix for single block

### ISSUE THREAD

**Issue by phongle1205** [seancfoley/IPAddress#10] opened 2018-10-16 10:03 UTC
On version 4.2.0, the following code will throw ArrayIndexOutOfBoundsException:4

`IPAddress ipAddress = (new IPAddressString("1.2.3.4")).toAddress().assignPrefixForSingleBlock();
ipAddress.toPrefixBlock();`

I am not family with network terms so I don't know if it is valid case.

**Comment by seancfoley** [comment] 2018-10-17 19:03
Yes, I've reproduced it.  It seems I fixed that issue 3 months ago but it's not part of a release yet.  

https://github.com/seancfoley/IPAddress/commit/4fc617b1d1a18002354cd2f145ecac6c48f73ad7#diff-7718cf164ef160f0e675d9e3a461ab73R1490

The fix is three lines of code as shown in that link.

		if(prefixedSegmentIndex >= segmentCount) {
			return true;
		}

I do intend to do another release quite soon, probably within the next couple of weeks, both on the version 4 branch and the main branch.  The fix will be in there and I will close this issue when that is done.

If you want an immediate fix, you could create a jar from the code that makes up the version 4 branch https://github.com/seancfoley/IPAddress/tree/v4 and just use that, since it includes the fix.

Or you could grab the 4.2 release source code, make that 3 line code change, and then use that.
https://github.com/seancfoley/IPAddress/releases/tag/v4.2.0

**Comment by seancfoley** [comment] 2018-11-02 22:07
This is fixed in version 4.3.0 and 5.0.0.

**Closed by seancfoley** 2018-11-02 22:07 UTC
