### ISSUE TITLE
IPAdress.isMultiple() is returning FALSE for IP CIDR range

### ISSUE THREAD

**Issue by Drizzt321** [seancfoley/IPAddress#54] opened 2020-12-21 22:09 UTC
I have some IP strings I'm using to match IPs, and I'm trying to use .isMultiple() to determine if the strings represent more than 1 IP (e.g. a CIDR address) or not. One of them is `35.35.35.0/23`, which is giving me FALSE. Likewise `35.35.33.0/23` is giving me FALSE, although `159.127.40.0/23` is giving me TRUE.

Been trying to debug/trace down into the library to see what the issue is, but it's slow going for me since I'm unfamiliar with how/where stuff is being done to split up IP addresses.

Example code:
```
public static void main(String[] args) {
    String ip = "35.35.35.0/23";

    IPAddress addr = new IPAddressString(ip).getAddress();
    System.out.println(ip + " is multiple " + addr.isMultiple());
}
```
Which gives me 
`35.35.35.0/16 is multiple false`

Using IPAdress version 5.3.3 via Maven

**Comment by seancfoley** [comment] 2020-12-27 02:23
This a duplicate of issues #26, issue #30,  issue #45, and issue #51 and also similar to issue #39 and issue #53.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-prefixed-ip-address-string-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#check-if-subnet-contains-address-or-subnet) - see enclosingBlockContains() in particular.

In summary, 
35.35.35.0/23 is the same as 35.35.35.0, just a single address, because the host is not zero.  35.35.34.0/23 is the subnet of 512 addresses because the host is zero.  Same goes with 35.35.35.0/16.  35.35.35.0/16 is one address, 35.35.0.0/16 is many.  If you want to convert to the subnet, then use toPrefixBlock.
```java
IPAddress addr = new IPAddressString("35.35.35.0/23").getAddress();	
System.out.println(addr + " has count " + addr.getCount());
addr = new IPAddressString("35.35.34.0/23").getAddress();	
System.out.println(addr + " has count " + addr.getCount());
addr = new IPAddressString("35.35.35.0/23").getAddress().toPrefixBlock();
System.out.println(addr + " has count " + addr.getCount());
```
Output:
```
35.35.35.0/23 has count 1
35.35.34.0/23 has count 512
35.35.34.0/23 has count 512
```

**Closed by seancfoley** 2020-12-27 02:23 UTC

**Comment by Drizzt321** [comment] 2020-12-27 23:10
*facepalm*  Sorry about that. I saw those tickets, and then never bothered to check if the IP was the network IP, or actually a single IP.
